### ISSUE TITLE
Products View

### ISSUE THREAD

**Issue by jesseelizabeth** [gh-dream-team/Shopper#2]
As a visitor, I want to see all of the products, so that I can choose one to get more details or add one to my cart

Sub-tasks:
- [ ] an Express route on the backend (GET `/api/products`) to server up the name, description, price, quantity, imageUrl from our database #1
- [ ] a React component for Products #2 
- [ ] a Redux sub-reducer for fetching all products   (thunk) #3
-  [ ] a database that holds all of our products #4
